export const staticPaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot_password: "/forgot-password",
  reset_password: "/reset-password",
  about: "/about",
  term: "/terms",
  policy: "/policy",
  profile: "/user-profile",
  all_article_category: "/article/categories",
  all_article_tags: "/article/tags",
  all_article: "/article/categories/all-articles",
  achievements: "/user/achievements",
  my_hall_of_fame: "/hall-of-fame",
  maintenance: "/maintenance",
  not_found: "/404",
  shop: "/shop",
};
